// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Div: typeof import('vue-termui')['TuiBox']
    Home: typeof import('./src/components/Home.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    Link: typeof import('vue-termui')['TuiLink']
    Logo: typeof import('./src/components/Logo.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    Output: typeof import('./src/components/Output.vue')['default']
    Repl: typeof import('./src/components/Repl.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Span: typeof import('vue-termui')['TuiText']
  }
}
