// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Components: typeof import('./src/components/Components.vue')['default']
    Div: typeof import('vue-termui')['TuiBox']
    Home: typeof import('./src/components/Home.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    Output: typeof import('./src/components/Output.vue')['default']
    Repl: typeof import('./src/components/Repl.vue')['default']
    Span: typeof import('vue-termui')['TuiText']
  }
}
